from . import res_config_settings
from . import tourism_destination
from . import tourism_tour_package
from . import tourism_itinerary_line
from . import tourism_departure
from . import tourism_review
from . import tourism_booking
from . import tourism_vehicle
from . import tourism_transport_assignment
from . import res_partner
